---
title: "Untitled"
author: "Josh"
date: "2024-06-18"
output: pdf_document
---

```{r include=FALSE}

rm(list = ls()) # Clean your environment:
gc() # garbage collection - It can be useful to call gc after a large object has been removed, as this may prompt R to return memory to the operating system.
library(tidyverse)
library(readr)
list.files('code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))
```

### Loading the data

```{r include=FALSE}
baby_names <- read_rds("data/Baby_Names_By_US_State.rds")
charts <- read_rds("data/charts.rds")
hbo_titles <- read_rds("data/HBO_titles.rds")
hbo_credits <- read_rds("data/HBO_credits.rds")
```

## Now can begin with data work

```{r}
# the core idea here is that a toy design agency that wants to do data analytics around baby naming trends in the US through the years in order to have a better understanding on how naming trends will help them better predict which character names to use in naming their toys.

# Step 1 is to first show a time-series representation of the rank-correlation between each year’s 25 most popular boys’ and girls’ namesand that of the next 3 years.
# do this using a Spearman rank correlation
# and then  confirm or deny their suspicion that since the 1990s, popular name trends have been slower to persist than in earlier decades.

# First I am 

national <- baby_names %>%
  group_by(Year, Gender, Name) %>%
  summarize(Count = sum(Count)) %>%
  ungroup()


plot_data_M <- spearman_corr(national, gender = "M")
plot_data_F <- spearman_corr(national, gender = "F")

plots <- ts_corr_plotter(plot_data_M, plot_data_F)
plots





  
    
 






```

